-- Regression tests with disposable fixtures; no persistent writes.
begin;
create temp table publishing_fixture(a uuid,b uuid,young uuid,admin_id uuid,d uuid,p uuid,platform uuid,category uuid,tag uuid);
insert into publishing_fixture values(gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),gen_random_uuid(),(select id from public.platforms where active limit 1),(select id from public.categories where active limit 1),(select id from public.tags limit 1));
grant select on publishing_fixture to authenticated,anon,service_role;
insert into public.tags(name,slug) select 'test-'||p,'test-'||p from publishing_fixture;
update publishing_fixture set tag=(select id from public.tags where slug='test-'||publishing_fixture.p);
insert into auth.users(id,email,created_at,raw_user_meta_data) select a,a||'@publishing-test.invalid',now()-interval '1 day','{}'::jsonb from publishing_fixture union all select b,b||'@publishing-test.invalid',now()-interval '1 day','{}'::jsonb from publishing_fixture union all select young,young||'@publishing-test.invalid',now(),'{}'::jsonb from publishing_fixture union all select admin_id,admin_id||'@publishing-test.invalid',now()-interval '1 day','{}'::jsonb from publishing_fixture;
insert into public.developer_profiles(id,owner_id,name,slug) select d,a,'Publishing Test','test-'||d from publishing_fixture;
insert into public.developer_profiles(owner_id,name,slug) select young,'Young Test','test-'||young from publishing_fixture;
insert into public.user_roles(user_id,role) select admin_id,'admin' from publishing_fixture;
set local role service_role;
do $$ declare f record; payload jsonb; result jsonb; upload jsonb; initial integer; begin
 select * into f from publishing_fixture;
 payload:=jsonb_build_object('id',f.p,'developer_id',f.d,'name','Test Plugin','slug','test-'||f.p,'short_description','A test plugin for regression checks.','platform_id',f.platform,'listing_type','direct_sale','categories',jsonb_build_array(f.category),'tags',jsonb_build_array(f.tag),'full_description','A sufficiently detailed plugin description for testing.','compatibility','Blender 4+','moderation_status','approved','downloads_count',9999,'price',99);
 result:=public.publishing_action(f.a,'create',payload);
 if result->>'moderation_status'<>'draft' or (result->>'downloads_count')::int<>0 or (result->>'price')::numeric<>0 then raise exception 'Protected field injection'; end if;
 result:=public.publishing_action(f.a,'create',payload);
 if (select count(*) from public.plugins where id=f.p)<>1 then raise exception 'Duplicate draft'; end if;
 begin perform public.publishing_action(f.b,'save',payload); raise exception 'Foreign save allowed'; exception when raise_exception then if SQLERRM='Foreign save allowed' then raise; end if; end;
 begin perform public.publishing_action(f.young,'create',payload||jsonb_build_object('id',gen_random_uuid(),'developer_id',(select id from public.developer_profiles where owner_id=f.young))); raise exception 'Young account allowed'; exception when raise_exception then if SQLERRM not like '%5 minutes%' then raise; end if; end;
 begin perform public.publishing_action(f.a,'submit',jsonb_build_object('id',f.p)); raise exception 'Incomplete submit allowed'; exception when raise_exception then if SQLERRM='Incomplete submit allowed' then raise; end if; end;
 perform public.publishing_action(f.a,'version',jsonb_build_object('id',f.p,'version_number','1.0.0','changelog','Initial release','compatibility','Blender 4+'));
 upload:=public.publishing_action(f.a,'reserve_upload',jsonb_build_object('id',f.p,'kind','zip','name','test.zip','mime','application/zip','size',100));
 -- Server validation is tested separately; emulate its trusted finalization here.
 perform public.publishing_action(f.a,'finish_upload',jsonb_build_object('id',f.p,'upload_id',upload->>'id'));
 upload:=public.publishing_action(f.a,'reserve_upload',jsonb_build_object('id',f.p,'kind','logo','name','logo.png','mime','image/png','size',100));
 perform public.publishing_action(f.a,'finish_upload',jsonb_build_object('id',f.p,'upload_id',upload->>'id','public_url','https://example.com/logo.png'));
 upload:=public.publishing_action(f.a,'reserve_upload',jsonb_build_object('id',f.p,'kind','screenshot','name','screen.png','mime','image/png','size',100));
 perform public.publishing_action(f.a,'finish_upload',jsonb_build_object('id',f.p,'upload_id',upload->>'id','public_url','https://example.com/screen.png'));
 upload:=public.publishing_action(f.a,'reserve_upload',jsonb_build_object('id',f.p,'kind','cover','name','cover.png','mime','image/png','size',100));
 perform public.publishing_action(f.a,'finish_upload',jsonb_build_object('id',f.p,'upload_id',upload->>'id','public_url','https://example.com/cover.png'));
 upload:=public.publishing_action(f.a,'reserve_upload',jsonb_build_object('id',f.p,'kind','cover','name','cover-new.png','mime','image/png','size',100));
 perform public.publishing_action(f.a,'finish_upload',jsonb_build_object('id',f.p,'upload_id',upload->>'id','public_url','https://example.com/cover-new.png'));
 if (select count(*) from public.plugin_assets where plugin_id=f.p and asset_type='cover')<>1 then raise exception 'Duplicate covers'; end if;
 perform public.publishing_action(f.a,'download',jsonb_build_object('id',f.p));
 begin perform public.publishing_action(f.b,'download',jsonb_build_object('id',f.p)); raise exception 'Draft download allowed'; exception when raise_exception then if SQLERRM='Draft download allowed' then raise; end if; end;
 perform public.publishing_action(f.a,'submit',jsonb_build_object('id',f.p));
 if (select moderation_status from public.plugins where id=f.p)<>'pending_review' or (select status from public.plugin_versions where plugin_id=f.p)<>'pending_review' then raise exception 'Submit statuses incorrect'; end if;
 begin perform public.publishing_action(f.a,'save',payload); raise exception 'Pending edit allowed'; exception when raise_exception then if SQLERRM='Pending edit allowed' then raise; end if; end;
 begin perform public.publishing_action(f.b,'download',jsonb_build_object('id',f.p)); raise exception 'Pending download allowed'; exception when raise_exception then if SQLERRM='Pending download allowed' then raise; end if; end;
 perform public.admin_moderate_plugin(f.admin_id,f.p,'rejected','Test rejection');
 perform public.publishing_action(f.a,'revise',jsonb_build_object('id',f.p));
 perform public.publishing_action(f.a,'submit',jsonb_build_object('id',f.p));
 perform public.admin_moderate_plugin(f.admin_id,f.p,'approved');
 if not exists(select 1 from public.plugin_versions where plugin_id=f.p and status='published' and is_current) then raise exception 'Approval did not publish version'; end if;
 if (select current_version from public.plugins where id=f.p)<>'1.0.0' then raise exception 'Current version out of sync'; end if;
 if public.review_download_eligibility(f.b,f.p) then raise exception 'Review allowed before download'; end if;
 begin perform public.save_plugin_review(f.b,f.p,5,'',''); raise exception 'Review without download allowed'; exception when raise_exception then if SQLERRM='Review without download allowed' then raise; end if; end;
 perform public.publishing_action(f.b,'download',jsonb_build_object('id',f.p,'file_path','attacker/path'));
 perform public.publishing_action(f.b,'record_download',jsonb_build_object('id',f.p));
 perform public.publishing_action(f.b,'record_download',jsonb_build_object('id',f.p));
 perform public.publishing_action(f.a,'record_download',jsonb_build_object('id',f.p));
 if (select downloads_count from public.plugins where id=f.p)<>1 then raise exception 'Download deduplication failed'; end if;
 if not public.review_download_eligibility(f.b,f.p) then raise exception 'Downloader cannot review'; end if;
 if public.review_download_eligibility(f.a,f.p) then raise exception 'Author can review'; end if;
 perform public.save_plugin_review(f.b,f.p,5,'First','Initial review');
 perform public.save_plugin_review(f.b,f.p,4,'Updated','Edited review');
 if (select count(*) from public.reviews where plugin_id=f.p)<>1 then raise exception 'Duplicate reviews'; end if;
 if (select rating_average from public.plugins where id=f.p)<>4 then raise exception 'Rating aggregate incorrect'; end if;
 update public.reviews set status='hidden' where plugin_id=f.p;
 begin perform public.save_plugin_review(f.b,f.p,5,'',''); raise exception 'Hidden review revived'; exception when raise_exception then if SQLERRM='Hidden review revived' then raise; end if; end;
 if (select status from public.reviews where plugin_id=f.p)<>'hidden' then raise exception 'Moderation lost'; end if;
 update public.plugins set listing_type='external_listing' where id=f.p;
 if public.review_download_eligibility(f.b,f.p) then raise exception 'External review without purchase allowed'; end if;
 insert into public.purchases(user_id,plugin_id,developer_id,status) values(f.b,f.p,f.d,'paid');
 if not public.review_download_eligibility(f.b,f.p) then raise exception 'External purchase eligibility lost'; end if;
 delete from public.purchases where plugin_id=f.p;
 update public.plugins set listing_type='direct_sale' where id=f.p;
 update public.plugins set pricing_model='paid' where id=f.p;
 begin perform public.publishing_action(f.b,'download',jsonb_build_object('id',f.p)); raise exception 'Unpaid download allowed'; exception when raise_exception then if SQLERRM='Unpaid download allowed' then raise; end if; end;
 insert into public.purchases(user_id,plugin_id,developer_id,status) values(f.b,f.p,f.d,'partially_refunded');
 perform public.publishing_action(f.b,'download',jsonb_build_object('id',f.p));
 update public.purchases set status='refunded' where plugin_id=f.p;
 begin perform public.publishing_action(f.b,'download',jsonb_build_object('id',f.p)); raise exception 'Refunded download allowed'; exception when raise_exception then if SQLERRM='Refunded download allowed' then raise; end if; end;
 perform public.admin_moderate_plugin(f.admin_id,f.p,'suspended');
 begin perform public.publishing_action(f.b,'download',jsonb_build_object('id',f.p)); raise exception 'Suspended download allowed'; exception when raise_exception then if SQLERRM='Suspended download allowed' then raise; end if; end;
end; $$;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select b::text from publishing_fixture),true);
do $$ declare f record; begin
 select * into f from publishing_fixture;
 if exists(select 1 from public.plugins where id=f.p) then raise exception 'Private plugin leaked'; end if;
 begin perform public.publishing_action(f.a,'download',jsonb_build_object('id',f.p)); raise exception 'Direct RPC allowed'; exception when insufficient_privilege then null; end;
 begin perform public.save_plugin_review(f.b,f.p,5,'',''); raise exception 'Direct review RPC allowed'; exception when insufficient_privilege then null; end;
 begin insert into public.reviews(plugin_id,user_id,rating) values(f.p,f.b,5); raise exception 'Direct review insert allowed'; exception when insufficient_privilege then null; end;
 begin update public.plugins set moderation_status='approved' where id=f.p; raise exception 'Direct write allowed'; exception when insufficient_privilege then null; end;
 begin update public.plugin_versions set is_current=true where plugin_id=f.p; raise exception 'Version write allowed'; exception when insufficient_privilege then null; end;
 begin insert into storage.objects(bucket_id,name) values('plugin-files','attacker.zip'); raise exception 'Direct Storage upload allowed'; exception when insufficient_privilege then null; end;
 begin perform count(*) from public.plugin_uploads; raise exception 'Upload records leaked'; exception when insufficient_privilege then null; end;
end; $$;
set local role anon;
select set_config('request.jwt.claim.sub','',true);
do $$ begin
 begin perform public.publishing_action(null,'create','{}'); raise exception 'Anonymous RPC allowed'; exception when insufficient_privilege then null; end;
end; $$;
set local role authenticated;
select set_config('request.jwt.claim.sub',(select a::text from publishing_fixture),true);
do $$ begin
 if (select count(*) from public.plugin_versions where plugin_id=(select p from publishing_fixture))<>1 then raise exception 'Owner version visibility failed'; end if;
 if (select count(*) from public.plugin_assets where plugin_id=(select p from publishing_fixture))<>3 then raise exception 'Owner media visibility failed'; end if;
end; $$;
rollback;
