/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as PlatformSlugRouteImport } from './routes/platform.$slug'
import { Route as PluginsIndexRouteImport } from './routes/plugins.index'
import { Route as PluginsSlugRouteImport } from './routes/plugins.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSlugRoute = PlatformSlugRouteImport.update({
  id: '/platform/$slug',
  path: '/platform/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsSlugRoute = PluginsSlugRouteImport.update({
  id: '/plugins/$slug',
  path: '/plugins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/category/$slug': typeof CategorySlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/plugins/': typeof PluginsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/category/$slug': typeof CategorySlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/plugins': typeof PluginsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/category/$slug': typeof CategorySlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/plugins/': typeof PluginsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/category/$slug'
    | '/platform/$slug'
    | '/plugins/$slug'
    | '/plugins/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/category/$slug'
    | '/platform/$slug'
    | '/plugins/$slug'
    | '/plugins'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/category/$slug'
    | '/platform/$slug'
    | '/plugins/$slug'
    | '/plugins/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  CategorySlugRoute: typeof CategorySlugRoute
  PlatformSlugRoute: typeof PlatformSlugRoute
  PluginsSlugRoute: typeof PluginsSlugRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/$slug': {
      id: '/platform/$slug'
      path: '/platform/$slug'
      fullPath: '/platform/$slug'
      preLoaderRoute: typeof PlatformSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$slug': {
      id: '/plugins/$slug'
      path: '/plugins/$slug'
      fullPath: '/plugins/$slug'
      preLoaderRoute: typeof PluginsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  CategorySlugRoute: CategorySlugRoute,
  PlatformSlugRoute: PlatformSlugRoute,
  PluginsSlugRoute: PluginsSlugRoute,
  PluginsIndexRoute: PluginsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
