/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as PublishingRequirementsRouteImport } from './routes/publishing-requirements'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedFavoritesRouteImport } from './routes/_authenticated/favorites'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedWishlistRouteImport } from './routes/_authenticated/wishlist'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as DeveloperDashboardRouteImport } from './routes/developer.dashboard'
import { Route as DevelopersSlugRouteImport } from './routes/developers.$slug'
import { Route as PlatformSlugRouteImport } from './routes/platform.$slug'
import { Route as PluginsIndexRouteImport } from './routes/plugins.index'
import { Route as PluginsSlugRouteImport } from './routes/plugins.$slug'
import { Route as DeveloperPluginsIdAnalyticsRouteImport } from './routes/developer.plugins.$id.analytics'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const PublishingRequirementsRoute = PublishingRequirementsRouteImport.update({
  id: '/publishing-requirements',
  path: '/publishing-requirements',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFavoritesRoute = AuthenticatedFavoritesRouteImport.update({
  id: '/favorites',
  path: '/favorites',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWishlistRoute = AuthenticatedWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperDashboardRoute = DeveloperDashboardRouteImport.update({
  id: '/developer/dashboard',
  path: '/developer/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DevelopersSlugRoute = DevelopersSlugRouteImport.update({
  id: '/developers/$slug',
  path: '/developers/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformSlugRoute = PlatformSlugRouteImport.update({
  id: '/platform/$slug',
  path: '/platform/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsIndexRoute = PluginsIndexRouteImport.update({
  id: '/plugins/',
  path: '/plugins/',
  getParentRoute: () => rootRouteImport,
} as any)
const PluginsSlugRoute = PluginsSlugRouteImport.update({
  id: '/plugins/$slug',
  path: '/plugins/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeveloperPluginsIdAnalyticsRoute =
  DeveloperPluginsIdAnalyticsRouteImport.update({
    id: '/developer/plugins/$id/analytics',
    path: '/developer/plugins/$id/analytics',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/publishing-requirements': typeof PublishingRequirementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/developer/dashboard': typeof DeveloperDashboardRoute
  '/developers/$slug': typeof DevelopersSlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/plugins/': typeof PluginsIndexRoute
  '/developer/plugins/$id/analytics': typeof DeveloperPluginsIdAnalyticsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/publishing-requirements': typeof PublishingRequirementsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/favorites': typeof AuthenticatedFavoritesRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/wishlist': typeof AuthenticatedWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/developer/dashboard': typeof DeveloperDashboardRoute
  '/developers/$slug': typeof DevelopersSlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/plugins': typeof PluginsIndexRoute
  '/developer/plugins/$id/analytics': typeof DeveloperPluginsIdAnalyticsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/publishing-requirements': typeof PublishingRequirementsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/favorites': typeof AuthenticatedFavoritesRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/wishlist': typeof AuthenticatedWishlistRoute
  '/category/$slug': typeof CategorySlugRoute
  '/developer/dashboard': typeof DeveloperDashboardRoute
  '/developers/$slug': typeof DevelopersSlugRoute
  '/platform/$slug': typeof PlatformSlugRoute
  '/plugins/$slug': typeof PluginsSlugRoute
  '/plugins/': typeof PluginsIndexRoute
  '/developer/plugins/$id/analytics': typeof DeveloperPluginsIdAnalyticsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/publishing-requirements'
    | '/dashboard'
    | '/favorites'
    | '/library'
    | '/wishlist'
    | '/category/$slug'
    | '/developer/dashboard'
    | '/developers/$slug'
    | '/platform/$slug'
    | '/plugins/$slug'
    | '/plugins/'
    | '/developer/plugins/$id/analytics'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/publishing-requirements'
    | '/dashboard'
    | '/favorites'
    | '/library'
    | '/wishlist'
    | '/category/$slug'
    | '/developer/dashboard'
    | '/developers/$slug'
    | '/platform/$slug'
    | '/plugins/$slug'
    | '/plugins'
    | '/developer/plugins/$id/analytics'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/auth'
    | '/publishing-requirements'
    | '/_authenticated/dashboard'
    | '/_authenticated/favorites'
    | '/_authenticated/library'
    | '/_authenticated/wishlist'
    | '/category/$slug'
    | '/developer/dashboard'
    | '/developers/$slug'
    | '/platform/$slug'
    | '/plugins/$slug'
    | '/plugins/'
    | '/developer/plugins/$id/analytics'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  PublishingRequirementsRoute: typeof PublishingRequirementsRoute
  CategorySlugRoute: typeof CategorySlugRoute
  DeveloperDashboardRoute: typeof DeveloperDashboardRoute
  DevelopersSlugRoute: typeof DevelopersSlugRoute
  PlatformSlugRoute: typeof PlatformSlugRoute
  PluginsSlugRoute: typeof PluginsSlugRoute
  PluginsIndexRoute: typeof PluginsIndexRoute
  DeveloperPluginsIdAnalyticsRoute: typeof DeveloperPluginsIdAnalyticsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/publishing-requirements': {
      id: '/publishing-requirements'
      path: '/publishing-requirements'
      fullPath: '/publishing-requirements'
      preLoaderRoute: typeof PublishingRequirementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/favorites': {
      id: '/_authenticated/favorites'
      path: '/favorites'
      fullPath: '/favorites'
      preLoaderRoute: typeof AuthenticatedFavoritesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/wishlist': {
      id: '/_authenticated/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AuthenticatedWishlistRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/dashboard': {
      id: '/developer/dashboard'
      path: '/developer/dashboard'
      fullPath: '/developer/dashboard'
      preLoaderRoute: typeof DeveloperDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developers/$slug': {
      id: '/developers/$slug'
      path: '/developers/$slug'
      fullPath: '/developers/$slug'
      preLoaderRoute: typeof DevelopersSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform/$slug': {
      id: '/platform/$slug'
      path: '/platform/$slug'
      fullPath: '/platform/$slug'
      preLoaderRoute: typeof PlatformSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/': {
      id: '/plugins/'
      path: '/plugins'
      fullPath: '/plugins/'
      preLoaderRoute: typeof PluginsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plugins/$slug': {
      id: '/plugins/$slug'
      path: '/plugins/$slug'
      fullPath: '/plugins/$slug'
      preLoaderRoute: typeof PluginsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/developer/plugins/$id/analytics': {
      id: '/developer/plugins/$id/analytics'
      path: '/developer/plugins/$id/analytics'
      fullPath: '/developer/plugins/$id/analytics'
      preLoaderRoute: typeof DeveloperPluginsIdAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedFavoritesRoute: typeof AuthenticatedFavoritesRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedWishlistRoute: typeof AuthenticatedWishlistRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedFavoritesRoute: AuthenticatedFavoritesRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedWishlistRoute: AuthenticatedWishlistRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  PublishingRequirementsRoute: PublishingRequirementsRoute,
  CategorySlugRoute: CategorySlugRoute,
  DeveloperDashboardRoute: DeveloperDashboardRoute,
  DevelopersSlugRoute: DevelopersSlugRoute,
  PlatformSlugRoute: PlatformSlugRoute,
  PluginsSlugRoute: PluginsSlugRoute,
  PluginsIndexRoute: PluginsIndexRoute,
  DeveloperPluginsIdAnalyticsRoute: DeveloperPluginsIdAnalyticsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
