create table if not exists public.site_analytics_events (
  id bigint generated by default as identity primary key,
  event_kind text not null check (event_kind in ('page_view', 'excluded_bot')),
  path text not null check (path like '/%' and length(path) <= 1024),
  plugin_id uuid references public.plugins(id) on delete set null,
  visitor_hash text,
  session_hash text,
  referrer_host text check (referrer_host is null or length(referrer_host) <= 255),
  excluded_reason text check (excluded_reason is null or length(excluded_reason) <= 120),
  created_at timestamptz not null default now(),
  constraint site_analytics_identity_shape check (
    (event_kind = 'page_view' and visitor_hash ~ '^[0-9a-f]{64}$' and session_hash ~ '^[0-9a-f]{64}$' and excluded_reason is null)
    or
    (event_kind = 'excluded_bot' and visitor_hash is null and session_hash is null and excluded_reason is not null)
  )
);

alter table public.site_analytics_events enable row level security;
revoke all on table public.site_analytics_events from public, anon, authenticated;
grant select, insert on table public.site_analytics_events to service_role;
grant usage, select on sequence public.site_analytics_events_id_seq to service_role;

create index if not exists site_analytics_events_created_at_idx
  on public.site_analytics_events (created_at desc);
create index if not exists site_analytics_events_path_created_idx
  on public.site_analytics_events (path, created_at desc)
  where event_kind = 'page_view';
create index if not exists site_analytics_events_plugin_created_idx
  on public.site_analytics_events (plugin_id, created_at desc)
  where event_kind = 'page_view' and plugin_id is not null;
create index if not exists site_analytics_events_visitor_created_idx
  on public.site_analytics_events (visitor_hash, created_at desc)
  where event_kind = 'page_view';
create index if not exists site_analytics_events_session_created_idx
  on public.site_analytics_events (session_hash, created_at desc)
  where event_kind = 'page_view';

create or replace function public.record_site_page_view(
  _path text,
  _plugin_id uuid,
  _visitor_hash text,
  _session_hash text,
  _referrer_host text
)
returns boolean
language plpgsql
security invoker
set search_path = public, private
as $$
begin
  if _path !~ '^/' or length(_path) > 1024
     or _visitor_hash !~ '^[0-9a-f]{64}$'
     or _session_hash !~ '^[0-9a-f]{64}$' then
    raise exception 'Invalid analytics event.';
  end if;

  perform pg_advisory_xact_lock(hashtext(_session_hash || ':' || _path));
  if exists (
    select 1 from public.site_analytics_events
    where event_kind = 'page_view'
      and session_hash = _session_hash
      and path = _path
      and created_at >= now() - interval '30 seconds'
  ) then
    return false;
  end if;

  insert into public.site_analytics_events (
    event_kind, path, plugin_id, visitor_hash, session_hash, referrer_host
  ) values (
    'page_view', _path, _plugin_id, _visitor_hash, _session_hash, nullif(_referrer_host, '')
  );
  return true;
end;
$$;

revoke all on function public.record_site_page_view(text, uuid, text, text, text) from public, anon, authenticated;
grant execute on function public.record_site_page_view(text, uuid, text, text, text) to service_role;

create or replace function public.admin_site_analytics(
  _actor_id uuid,
  _range text default '24h'
)
returns jsonb
language plpgsql
security invoker
set search_path = public
as $$
declare
  _since timestamptz;
  _page_views bigint;
  _sessions bigint;
  _visitors bigint;
begin
  if not private.has_role(_actor_id, 'admin'::public.app_role) then
    raise exception 'Administrator access is required.' using errcode = '42501';
  end if;

  _since := case _range
    when '5m' then now() - interval '5 minutes'
    when '30m' then now() - interval '30 minutes'
    when '24h' then now() - interval '24 hours'
    when '7d' then now() - interval '7 days'
    when '30d' then now() - interval '30 days'
    else null
  end;
  if _since is null then raise exception 'Unsupported analytics range.'; end if;

  select count(*), count(distinct visitor_hash), count(distinct session_hash)
    into _page_views, _visitors, _sessions
  from public.site_analytics_events
  where created_at >= _since and event_kind = 'page_view';

  return jsonb_build_object(
    'range', _range,
    'generatedAt', now(),
    'uniqueVisitors', _visitors,
    'pageViews', _page_views,
    'sessions', _sessions,
    'pagesPerSession', case when _sessions = 0 then 0 else round(_page_views::numeric / _sessions, 2) end,
    'excludedBotTraffic', (
      select count(*) from public.site_analytics_events
      where created_at >= _since and event_kind = 'excluded_bot'
    ),
    'topPages', coalesce((
      select jsonb_agg(jsonb_build_object('path', path, 'views', views) order by views desc, path)
      from (
        select path, count(*)::bigint as views
        from public.site_analytics_events
        where created_at >= _since and event_kind = 'page_view'
        group by path order by views desc, path limit 10
      ) q
    ), '[]'::jsonb),
    'topPlugins', coalesce((
      select jsonb_agg(jsonb_build_object('id', id, 'name', name, 'slug', slug, 'views', views) order by views desc, name)
      from (
        select p.id, p.name, p.slug, count(*)::bigint as views
        from public.site_analytics_events e
        join public.plugins p on p.id = e.plugin_id
        where e.created_at >= _since and e.event_kind = 'page_view'
        group by p.id, p.name, p.slug order by views desc, p.name limit 10
      ) q
    ), '[]'::jsonb),
    'referrers', coalesce((
      select jsonb_agg(jsonb_build_object('source', source, 'views', views) order by views desc, source)
      from (
        select coalesce(referrer_host, 'Direct') as source, count(*)::bigint as views
        from public.site_analytics_events
        where created_at >= _since and event_kind = 'page_view'
        group by coalesce(referrer_host, 'Direct') order by views desc, source limit 10
      ) q
    ), '[]'::jsonb)
  );
end;
$$;

revoke all on function public.admin_site_analytics(uuid, text) from public, anon, authenticated;
grant execute on function public.admin_site_analytics(uuid, text) to service_role;

comment on table public.site_analytics_events is
  'Privacy-preserving first-party site traffic. Stores pseudonymous hashes only; no raw IP, user agent, or account identity.';
